"""second migration

Revision ID: e30b50efa110
Revises: 334e0ceb38f2
Create Date: 2024-06-30 22:50:33.028470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30b50efa110'
down_revision = '334e0ceb38f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Vacancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy', sa.String(length=200), nullable=False),
    sa.Column('employer', sa.String(length=300), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=False),
    sa.Column('salaryFrom', sa.Integer(), nullable=True),
    sa.Column('salaryTo', sa.Integer(), nullable=True),
    sa.Column('requirement', sa.String(length=350), nullable=False),
    sa.Column('responsibility', sa.String(length=350), nullable=False),
    sa.Column('alternate_url', sa.String(length=120), nullable=True),
    sa.Column('time', sa.String(length=70), nullable=True),
    sa.Column('timeDay', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('resume')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('keywords', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('skills', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('experience', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('salary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='resume_pkey')
    )
    op.drop_table('Vacancy')
    # ### end Alembic commands ###
